### ISSUE TITLE
DRY localstorage helper

### ISSUE THREAD

**Issue by arisros** [rdsarjito/cart-app#3]
https://github.com/rdsarjito/cart-app/blob/5331016cc500de041c0f40991396626081683d42/src/reducers/categoryReducer.js#L5

Can we build helper to make it DRY, and make this function more generic. Because this function almost same with other modules

**Comment by rdsarjito** [comment]
Solved,
[https://github.com/rdsarjito/cart-app/commit/d74cb35376619979e055c78819a88fbb8a7efb63](url)
